from .dashboard_callback import dashboard_callback
from .spendings_callback import spendings_callback
#from .sidebar_callback import sidebar_callback
from .authentication_callback import authentication_callback
from .settings_callback import settings_callback
from .support_callback import support_callback
from .home_callback import home_callback
from .navbar_callback import navbar_callback
from .test_callback import debug_callback
from .upload_callback import upload_callback
